// Code generated by "github.com/ming-0x0/accessor -type=Customer"; DO NOT EDIT.

package customer

import (
	"github.com/ming-0x0/hexago/domain/service_type"
	"github.com/ming-0x0/hexago/shared/domain/email"
)

// ID return id value
func (t Customer) ID() ID {
	return t.id
}

// CustomerName return customerName value
func (t Customer) CustomerName() string {
	return t.customerName
}

// Email return email value
func (t Customer) Email() email.Email {
	return t.email
}

// PhoneNumber return phoneNumber value
func (t Customer) PhoneNumber() string {
	return t.phoneNumber
}

// ServiceType return serviceType value
func (t Customer) ServiceType() service_type.ServiceType {
	return t.serviceType
}
