// Code generated by "accessor -type=Customer"; DO NOT EDIT.

package customer

import (
	"github.com/ming-0x0/hexago/internal/customer/domain/service_type"
	"github.com/ming-0x0/hexago/internal/customer/domain/status"
	"github.com/ming-0x0/hexago/internal/shared/domain/email"
	"github.com/ming-0x0/hexago/internal/shared/undefined"
)

// ID return id value
func (t Customer) ID() ID {
	return t.id
}

// CustomerName return customerName value
func (t Customer) CustomerName() string {
	return t.customerName
}

// Email return email value
func (t Customer) Email() email.Email {
	return t.email
}

// PhoneNumber return phoneNumber value
func (t Customer) PhoneNumber() string {
	return t.phoneNumber
}

// CompanyName return companyName value
func (t Customer) CompanyName() undefined.Undefined[string] {
	return t.companyName
}

// Message return message value
func (t Customer) Message() undefined.Undefined[string] {
	return t.message
}

// Note return note value
func (t Customer) Note() undefined.Undefined[string] {
	return t.note
}

// ServiceType return serviceType value
func (t Customer) ServiceType() service_type.ServiceType {
	return t.serviceType
}

// Status return status value
func (t Customer) Status() status.Status {
	return t.status
}
