// Code generated by "accessor -type=Banner"; DO NOT EDIT.

package banner

// ID return id value
func (t Banner) ID() ID {
	return t.id
}

// Name return name value
func (t Banner) Name() string {
	return t.name
}
